### ISSUE TITLE
Publish to Packagist.org?

### ISSUE THREAD

**Issue by danielbachhuber** [GaryJones/genesis-header-nav#9]
👋  I'd like to be able to `composer require` this plugin into a site. However, `composer require` against a bare Git repo is less than desirable.

Would you be open to publishing to [Packagist](https://packagist.org/)?

Thanks!

**Comment by GaryJones** [comment]
@danielbachhuber Been a while since I looked at this package, so let me know if you spot any issues to make usage of it easier.

It now exists on Packagist: https://packagist.org/packages/garyjones/genesis-header-nav

**Comment by danielbachhuber** [comment]
Thanks much!
